services:
  frontend:
      container_name: frontend
      build:
        context: ./frontend 
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/app
        - /app/node_modules
      depends_on:
        - user_service
      networks:
        - dev

  # Users setup
  user_service:
    container_name: user_service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - USER_DB_URI=${USER_DB_URI}
    depends_on:
      - users_db
    networks:
      - dev

  # Plans setup
  plans_service:
    container_name: plans_service
    build:
      context: ./plans_service
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PLANS_DB_URI=${PLANS_DB_URI}
    depends_on:
      - plans_db
    networks:
      - dev

  # DBs Setup
  plans_db:
    container_name: plans_db
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${PLANS_DB_USER}
      - POSTGRES_PASSWORD=${PLANS_DB_PASSWORD}
      - POSTGRES_DB=${PLANS_DB_NAME}
    volumes:
      - plans_db_data:/var/lib/postgresql/data
    networks:
      - dev

  users_db:
    container_name: users_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${USERS_DB_USER}
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
      - POSTGRES_DB=${USERS_DB_NAME}
    volumes:
      - users_db_data:/var/lib/postgresql/data
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - users_db
      - plans_db
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev

networks:
  dev:

volumes:
  users_db_data: {}
  plans_db_data: {}

    


